### ISSUE TITLE
Good accuracy / loss?

### ISSUE THREAD

**Issue by johnpaulbin** [argosopentech/argos-train#11]
What is a good amount of accuracy when training a model?
And, how much data did the Spanish model use?

**Comment by PJ-Finlay** [comment]
The Spanish model was trained an most of the big datasets on [Opus](https://opus.nlpl.eu/), I think around 100 million parallel sentences. For loss try asking on the [OpenNMT Forum](https://forum.opennmt.net/).

**Comment by johnpaulbin** [comment]
Awesome, thanks for the reply!
