### ISSUE TITLE
FineTuning from Argosmodel

### ISSUE THREAD

**Issue by johnpaulbin** [argosopentech/argos-train#12]
How can I finetune an existing argosmodel?

**Comment by PJ-Finlay** [comment]
The current Argos Translate models are converted for CTranslate2 so not straightforward, but I'm hoping to save and distribute checkpoints in the future. The underlying model is an OpenNMT model that can be trained in a day on a normal GPU to train one from scratch.


- https://forum.opennmt.net/t/domain-adaptation/4109

**Comment by johnpaulbin** [comment]
interesting, unfortunately I will have to train a new spanish model entirely and save the lastest checkpoint. Thanks for this info, though! (why not just save the latest checkpoint inside the argosmodel archive? or would that take up too much space?)

**Comment by PJ-Finlay** [comment]
I want to in the future, just an oversight when I was training them.
