### ISSUE TITLE
How to improve training?

### ISSUE THREAD

**Issue by qgustavor** [argosopentech/argos-train#13]
I commented in the language request discussion that Brazilian Portuguese is missing so I'm trying to train a en→pt_BR model. I will also train a es→pt_BR model to avoid pivoting around English. I'm having some issues:

My hardware is quite limited: I got 4 GB of GPU RAM, so, following the documentation I reduced both `batch_size` and `valid_batch_size` and I could train a model, but this model was quite bad (example: "Roses are red" was translated to "The queen is red"). I tried increasing `train_steps` but it's still not great (example: "Roses are red" was translated to "Roses é vermelho", i.e. "Roses (given name) is red"). Seems the issue was with the dataset I was using (subtitles), so I added more data... then the script crashed every time: my system only have 8 GB of RAM.

Is it possible to improve training under those hardware constraints? Or the only way is buying more RAM?

**Comment by qgustavor** [comment]
I tried reducing the corpus by randomly dropping lines from those (of course, the same line indexes are dropped in the source and target files) then I trained it three times, those are the results of each one:

1. I reduced the corpus by dropping 90% of all sources. For some reason [it returns "I don't know." for everything](https://pbs.twimg.com/media/FGRV7_pXMAcfUGG?format=png&name=large).
2. I changed the drop rate to be lower for small sources, larger for large sources, so large sources don't mess too much with the training (IIRC 90% drop rate for WikiMatrix, 80% drop rate for OpenSubtitles, 20% for TED, 80% for CAPES). It returned some results, but [this poem](https://pbs.twimg.com/media/FGUy-uhXIAUMg0w?format=png&name=small) was not translated well (it cannot handle names, like "Baba", changed "Violets" to "Christmas", etc). In [this line](https://pbs.twimg.com/media/FGUzfd_XoAEGMWC?format=png&name=small) I randomly got from Nagatoro anime it translated "sheep" as "snake", weird. In [this line](https://pbs.twimg.com/media/FGU0P3lX0AA4M27?format=png&name=small) from Komi-san it translated almost perfectly well, but ignored the "class" (which seems understandable as I'm using OpenSubtitles and repeating "class princess" in every line is not likely to be common in subtitles). In [this other line](https://pbs.twimg.com/media/FGU0duOWYAUC7NA?format=png&name=small), also from Komi-san, it messed up weirdly: the translation makes no sense ("Imgata's abilities is one of social skills.").
3. I changed the WikiMatrix drop rate to 85%, OpenSubtitles to 70%, TED to 10% and increased `train_steps` to `80000` and `early_stopping` to `6`. The [Baba is You poem](https://user-images.githubusercontent.com/1020670/145694922-2465f592-d976-431b-883e-3121ac4ee330.png) improved, now it better translates "red" as "vermelho" (but should be "vermelha" as roses are a feminine noun in Portuguese, also it should be "Rosas", not "Rose"), it ignored "Baba" and "Violets". It translated [Nagaroto's line](https://user-images.githubusercontent.com/1020670/145694980-45eaccbd-e868-4dd9-98d2-c4e2f2f68cc2.png) pretty well. The [first](
https://user-images.githubusercontent.com/1020670/145695046-d9c2a733-7a5b-4d8d-9bf1-1c4307daa9d8.png) and [second](https://user-images.githubusercontent.com/1020670/145695040-b2508ee7-c82f-4c25-9b10-18f368773711.png) are pretty much the same thing: the first is ok, the second is non-sense.

I don't know what I'm doing wrong. I hope you can help me.

**Comment by PJ-Finlay** [comment]
Nice experiments!

These are good questions, and it can be more art than science trying to figure out which tweaks will improve performance. The [OpenNMT Forum](https://forum.opennmt.net/) is a good resource to discuss what works and doesn't for translation models too.

The most straightforward and inexpensive way to train a model is probably vast.ai but if you already have access to specific hardware you may need to do some tweaks to get good performance.

**Comment by PJ-Finlay** [comment]
In general the best strategy for increasing quality is going to be increasing the quality and quantity of data.

It sounds like you're only using OpenSubtitles? You could try adding more datasets from Opus.

**Comment by qgustavor** [comment]
I understand. I has using more datasets (like WikiMatrix and TED). I even added some non-open datasets to match the content I want to translate in addition to those from OPUS. I think would be better spending money in better hardware resources instead of spending on GPU rentals, even if it's cheaper, because it will be more cost-efficient in the long run (8 GB RAM is just the minimal requirement for one of the programs I use at work).

Well, thanks for the help. I hope an official Brazilian Portuguese model gets released in the future.
