### ISSUE TITLE
Auto generated data-index.json

### ISSUE THREAD

**Issue by dingedi** [argosopentech/argos-train#14]
Rather than manually retrieving the data and adding them to the data-index.json, it would be simple I think to create a script that would automatically generate the data-index.json using the tables from https://opus.nlpl.eu/ and would automatically download the data? a kind of scrapper.

**Comment by PJ-Finlay** [comment]
This is definitely possible.

Currently I use the script in scripts/ to download Opus data into the data index but other/multiple approaches could work. I don't use all of the data on Opus since some have non-commercial licenses but this could be worked around.
