### ISSUE TITLE
Retrain on custom input

### ISSUE THREAD

**Issue by geekscrapy** [argosopentech/argos-train#15]
I would love to create a model which fits use in technical situations such as translation for Windows Event Logs and computer logs in general.

What's the best way to go about this?

Additionally as an example using a user account as the translation subject:
If the text `NT AUTHORITY\СИСТЕМА` is given, the uk>en translation truncates it to `NT AUTHORITY` as the output (it should be `NT AUTHORITY\SYSTEM`

**Comment by PJ-Finlay** [comment]
To [train on custom data](https://github.com/argosopentech/argos-train#data) you need to store your data in a `source` and `target` file with parallel text in each corresponding line. Then package the data in a .argosmodel package and add to `data-index.json`.

**Comment by geekscrapy** [comment]
Thanks! I'll give it a go.

In regards to the 2nd Q. Is there any way to stop the truncation?

**Comment by PJ-Finlay** [comment]
Of you have text you don't want translated the best strategy is probably to parse such that it is never passed through LibreTranslate for translation or to translate as HTML and put it inside a `span` or ` code` tag.

It looks like in this case the translation string just isn't what you wanted, the best strategy for this is to train a model with this specific translation and other similar data.
