### ISSUE TITLE
Support data from a local file

### ISSUE THREAD

**Issue by PJ-Finlay** [argosopentech/argos-train#24]
Currently Argos Train loads data from `data-index.json` from a remote HTTP server. I'd like to add support for loading data packages from a file on the local server like this:
```
"links": ["file:///home/argosopentech/Desktop/data-opensubtitles-en_de.argosdata"]
```

**Comment by rodti** [comment]
+1

**Comment by truongquoc** [comment]
Any update on this issue ?

**Comment by argosopentech** [comment]
I think this works now!
