### ISSUE TITLE
OpenNMT does not create checkpoints => index out of bounds error when training

### ISSUE THREAD

**Issue by LukasGaebler** [argosopentech/argos-train#28]
I cloned the repository and ran the argos-train-init script. 
After that, when running the argos-train command and using en to de as the languages, the data gets downloaded and the script  continues until an index out of bounds error. Error is below. The part with [] is the print of the opennmt_checkpoints in argostrain/train.py:165

![image](https://github.com/argosopentech/argos-train/assets/45339684/eb37b6bd-0b17-4f9b-918c-e7db7796b86c)

Ubuntu 22.04
Python 3.10.6

**Comment by argosopentech** [comment]
Try `PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:512` to fix the CUDA out of memory error. https://forum.opennmt.net/t/training-a-multilingual-model-with-opennmt-py/5242/13

The list out of range is caused by the out of memory crash.
